import { writeFileSync } from "node:fs";
import type { CapacitorConfig } from "@capacitor/cli";

// The iOS app is a native shell around the hosted web app (TanStack Start on
// Cloudflare), because the server functions need a server. The shell only
// needs the web app URL; Supabase keys live in the web host's env, never here.
//
// CAP_SERVER_URL comes from the git-ignored .env (see .env.example).
// `npx cap sync ios` copies the result into ios/App/App/capacitor.config.json
// (also git-ignored).
try {
  process.loadEnvFile(".env");
} catch {
  // No .env — fall back to the real environment.
}

const serverUrl = process.env.CAP_SERVER_URL;
if (!serverUrl) {
  throw new Error("Set CAP_SERVER_URL in .env (e.g. https://courtsie.<you>.workers.dev)");
}

// The offline page (server.errorPath) is a local file; it needs the server URL
// for its "try again" button. Generated here so it always matches CAP_SERVER_URL.
writeFileSync(
  "capacitor/www/server-url.js",
  `// Generated by capacitor.config.ts — do not edit.\nwindow.COURTSIE_SERVER_URL = ${JSON.stringify(serverUrl)};\n`,
);

const config: CapacitorConfig = {
  appId: process.env.CAP_APP_ID ?? "gr.innera.courtsie",
  appName: "Speak",
  // Local bundle: fallback index + the offline page.
  webDir: "capacitor/www",
  server: {
    url: serverUrl,
    // Plain http only for a dev server on your LAN (e.g. http://192.168.1.10:8080).
    cleartext: serverUrl.startsWith("http://"),
    // Shown when the web app can't be loaded (no internet, server down).
    errorPath: "offline.html",
  },
  ios: {
    // The web app pads itself with env(safe-area-inset-*) (viewport-fit=cover).
    contentInset: "never",
    scheme: "Courtsie",
    // No fixed colour behind the web view: the app follows the iPhone's Light / Dark setting (DESIGN.md).
  },
  plugins: {
    SplashScreen: {
      // Hidden by initNativeShell() once the web app has mounted; this is the upper bound.
      launchShowDuration: 3000,
      launchAutoHide: true,
      backgroundColor: "#0066CC",
      showSpinner: false,
    },
  },
};

export default config;
