/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMemoriesRouteImport } from './routes/_authenticated/memories'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRecordRouteImport } from './routes/_authenticated/record'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as ICodeRouteImport } from './routes/i.$code'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminTopicsRouteImport } from './routes/_authenticated/admin/topics'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedGroupsNewRouteImport } from './routes/_authenticated/groups.new'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedPPostIdRouteImport } from './routes/_authenticated/p.$postId'
import { Route as AuthenticatedSSectionIdRouteImport } from './routes/_authenticated/s.$sectionId'
import { Route as AuthenticatedTTopicIdRouteImport } from './routes/_authenticated/t.$topicId'
import { Route as AuthenticatedTalkIndexRouteImport } from './routes/_authenticated/talk.index'
import { Route as AuthenticatedTalkUserIdRouteImport } from './routes/_authenticated/talk.$userId'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedGGroupIdIndexRouteImport } from './routes/_authenticated/g.$groupId.index'
import { Route as AuthenticatedGGroupIdEditRouteImport } from './routes/_authenticated/g.$groupId.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordRoute = AuthenticatedRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ICodeRoute = ICodeRouteImport.update({
  id: '/i/$code',
  path: '/i/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTopicsRoute =
  AuthenticatedAdminTopicsRouteImport.update({
    id: '/admin/topics',
    path: '/admin/topics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsNewRoute = AuthenticatedGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/messages/$userId',
    path: '/messages/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPPostIdRoute = AuthenticatedPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSSectionIdRoute = AuthenticatedSSectionIdRouteImport.update({
  id: '/s/$sectionId',
  path: '/s/$sectionId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTTopicIdRoute = AuthenticatedTTopicIdRouteImport.update({
  id: '/t/$topicId',
  path: '/t/$topicId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalkIndexRoute = AuthenticatedTalkIndexRouteImport.update({
  id: '/talk/',
  path: '/talk/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalkUserIdRoute = AuthenticatedTalkUserIdRouteImport.update({
  id: '/talk/$userId',
  path: '/talk/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGGroupIdIndexRoute =
  AuthenticatedGGroupIdIndexRouteImport.update({
    id: '/g/$groupId/',
    path: '/g/$groupId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGGroupIdEditRoute =
  AuthenticatedGGroupIdEditRouteImport.update({
    id: '/g/$groupId/edit',
    path: '/g/$groupId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/record': typeof AuthenticatedRecordRoute
  '/search': typeof AuthenticatedSearchRoute
  '/student': typeof AuthenticatedStudentRoute
  '/i/$code': typeof ICodeRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/p/$postId': typeof AuthenticatedPPostIdRoute
  '/s/$sectionId': typeof AuthenticatedSSectionIdRoute
  '/t/$topicId': typeof AuthenticatedTTopicIdRoute
  '/talk/$userId': typeof AuthenticatedTalkUserIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/talk/': typeof AuthenticatedTalkIndexRoute
  '/g/$groupId/edit': typeof AuthenticatedGGroupIdEditRoute
  '/g/$groupId/': typeof AuthenticatedGGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/record': typeof AuthenticatedRecordRoute
  '/search': typeof AuthenticatedSearchRoute
  '/student': typeof AuthenticatedStudentRoute
  '/i/$code': typeof ICodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/p/$postId': typeof AuthenticatedPPostIdRoute
  '/s/$sectionId': typeof AuthenticatedSSectionIdRoute
  '/t/$topicId': typeof AuthenticatedTTopicIdRoute
  '/talk/$userId': typeof AuthenticatedTalkUserIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/talk': typeof AuthenticatedTalkIndexRoute
  '/g/$groupId/edit': typeof AuthenticatedGGroupIdEditRoute
  '/g/$groupId': typeof AuthenticatedGGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/memories': typeof AuthenticatedMemoriesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/record': typeof AuthenticatedRecordRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/i/$code': typeof ICodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/_authenticated/groups/new': typeof AuthenticatedGroupsNewRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/p/$postId': typeof AuthenticatedPPostIdRoute
  '/_authenticated/s/$sectionId': typeof AuthenticatedSSectionIdRoute
  '/_authenticated/t/$topicId': typeof AuthenticatedTTopicIdRoute
  '/_authenticated/talk/$userId': typeof AuthenticatedTalkUserIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/talk/': typeof AuthenticatedTalkIndexRoute
  '/_authenticated/g/$groupId/edit': typeof AuthenticatedGGroupIdEditRoute
  '/_authenticated/g/$groupId/': typeof AuthenticatedGGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/memories'
    | '/notifications'
    | '/profile'
    | '/record'
    | '/search'
    | '/student'
    | '/i/$code'
    | '/admin/reports'
    | '/admin/topics'
    | '/groups/new'
    | '/messages/$userId'
    | '/p/$postId'
    | '/s/$sectionId'
    | '/t/$topicId'
    | '/talk/$userId'
    | '/u/$username'
    | '/groups/'
    | '/messages/'
    | '/talk/'
    | '/g/$groupId/edit'
    | '/g/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/memories'
    | '/notifications'
    | '/profile'
    | '/record'
    | '/search'
    | '/student'
    | '/i/$code'
    | '/'
    | '/admin/reports'
    | '/admin/topics'
    | '/groups/new'
    | '/messages/$userId'
    | '/p/$postId'
    | '/s/$sectionId'
    | '/t/$topicId'
    | '/talk/$userId'
    | '/u/$username'
    | '/groups'
    | '/messages'
    | '/talk'
    | '/g/$groupId/edit'
    | '/g/$groupId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/memories'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/record'
    | '/_authenticated/search'
    | '/_authenticated/student'
    | '/i/$code'
    | '/_authenticated/'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/topics'
    | '/_authenticated/groups/new'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/p/$postId'
    | '/_authenticated/s/$sectionId'
    | '/_authenticated/t/$topicId'
    | '/_authenticated/talk/$userId'
    | '/_authenticated/u/$username'
    | '/_authenticated/groups/'
    | '/_authenticated/messages/'
    | '/_authenticated/talk/'
    | '/_authenticated/g/$groupId/edit'
    | '/_authenticated/g/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ICodeRoute: typeof ICodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memories': {
      id: '/_authenticated/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/record': {
      id: '/_authenticated/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthenticatedRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/i/$code': {
      id: '/i/$code'
      path: '/i/$code'
      fullPath: '/i/$code'
      preLoaderRoute: typeof ICodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/topics': {
      id: '/_authenticated/admin/topics'
      path: '/admin/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/new': {
      id: '/_authenticated/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthenticatedGroupsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$postId': {
      id: '/_authenticated/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof AuthenticatedPPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/s/$sectionId': {
      id: '/_authenticated/s/$sectionId'
      path: '/s/$sectionId'
      fullPath: '/s/$sectionId'
      preLoaderRoute: typeof AuthenticatedSSectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/t/$topicId': {
      id: '/_authenticated/t/$topicId'
      path: '/t/$topicId'
      fullPath: '/t/$topicId'
      preLoaderRoute: typeof AuthenticatedTTopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talk/': {
      id: '/_authenticated/talk/'
      path: '/talk'
      fullPath: '/talk/'
      preLoaderRoute: typeof AuthenticatedTalkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talk/$userId': {
      id: '/_authenticated/talk/$userId'
      path: '/talk/$userId'
      fullPath: '/talk/$userId'
      preLoaderRoute: typeof AuthenticatedTalkUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/g/$groupId/': {
      id: '/_authenticated/g/$groupId/'
      path: '/g/$groupId'
      fullPath: '/g/$groupId/'
      preLoaderRoute: typeof AuthenticatedGGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/g/$groupId/edit': {
      id: '/_authenticated/g/$groupId/edit'
      path: '/g/$groupId/edit'
      fullPath: '/g/$groupId/edit'
      preLoaderRoute: typeof AuthenticatedGGroupIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecordRoute: typeof AuthenticatedRecordRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminTopicsRoute: typeof AuthenticatedAdminTopicsRoute
  AuthenticatedGroupsNewRoute: typeof AuthenticatedGroupsNewRoute
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
  AuthenticatedPPostIdRoute: typeof AuthenticatedPPostIdRoute
  AuthenticatedSSectionIdRoute: typeof AuthenticatedSSectionIdRoute
  AuthenticatedTTopicIdRoute: typeof AuthenticatedTTopicIdRoute
  AuthenticatedTalkUserIdRoute: typeof AuthenticatedTalkUserIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedTalkIndexRoute: typeof AuthenticatedTalkIndexRoute
  AuthenticatedGGroupIdEditRoute: typeof AuthenticatedGGroupIdEditRoute
  AuthenticatedGGroupIdIndexRoute: typeof AuthenticatedGGroupIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecordRoute: AuthenticatedRecordRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminTopicsRoute: AuthenticatedAdminTopicsRoute,
  AuthenticatedGroupsNewRoute: AuthenticatedGroupsNewRoute,
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
  AuthenticatedPPostIdRoute: AuthenticatedPPostIdRoute,
  AuthenticatedSSectionIdRoute: AuthenticatedSSectionIdRoute,
  AuthenticatedTTopicIdRoute: AuthenticatedTTopicIdRoute,
  AuthenticatedTalkUserIdRoute: AuthenticatedTalkUserIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedTalkIndexRoute: AuthenticatedTalkIndexRoute,
  AuthenticatedGGroupIdEditRoute: AuthenticatedGGroupIdEditRoute,
  AuthenticatedGGroupIdIndexRoute: AuthenticatedGGroupIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ICodeRoute: ICodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
